
GET http://localhost:8123/Demystify/AntiGhostSystem/auth/signup
Content-Type: application/json
Authorization: Basic YWRzZmRzYWZmZDphZHNmYWRzCg==

{
    "grant_type" : "password",
    "client_id" : "My_Client_ID",
    "client_secret" : "My_Client_ID",
    "scope" : "admin",
    "username" : "fiftywebs",
    "password" : "pass"
}